[package]
name = "handmade_hero_interface"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { workspace = true }
thiserror = { workspace = true }
uom = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
